steps:
- name: 'golang'
  dir: limacharlie
  args: ['go', 'test', '.', '-v']
  env:
    - '_KEY=${_KEY}'
    - '_OID=${_OID}'
    - 'LC_CURRENT_ENV=test_env'
    - 'LC_OID=fba6e992-ce4f-4d9e-99dc-b548f00df7f9'
    - 'LC_UID=af4ddec0-c2e8-4db2-ba3f-f5e9a1aff3fd'
    - 'LC_API_KEY=843e80c8-e273-4b3e-93bd-41151b4b933a'
    - 'LC_CREDS_FILE_NO_ENV=tests/test_noenv.yaml'
    - 'LC_CREDS_FILE=tests/test.yaml'
options:
 machineType: 'N1_HIGHCPU_8'
